mywebsite/src/Entity/Album.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AlbumRepository")
 */
class Album
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $artiste;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_single;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Single", mappedBy="id_album")
     */
    private $id_single;

    public function __construct()
    {
        $this->id_single = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getArtiste(): ?string
    {
        return $this->artiste;
    }

    public function setArtiste(string $artiste): self
    {
        $this->artiste = $artiste;

        return $this;
    }

    public function getNbSingle(): ?int
    {
        return $this->nb_single;
    }

    public function setNbSingle(int $nb_single): self
    {
        $this->nb_single = $nb_single;

        return $this;
    }

    /**
     * @return Collection|Single[]
     */
    public function getIdSingle(): Collection
    {
        return $this->id_single;
    }

    public function addIdSingle(Single $idSingle): self
    {
        if (!$this->id_single->contains($idSingle)) {
            $this->id_single[] = $idSingle;
            $idSingle->setIdAlbum($this);
        }

        return $this;
    }

    public function removeIdSingle(Single $idSingle): self
    {
        if ($this->id_single->contains($idSingle)) {
            $this->id_single->removeElement($idSingle);
            // set the owning side to null (unless already changed)
            if ($idSingle->getIdAlbum() === $this) {
                $idSingle->setIdAlbum(null);
            }
        }

        return $this;
    }
}

mywebsite/src/Form/AlbumType.php
<?php

namespace App\Form;

use App\Entity\Album;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AlbumType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('artiste')
            ->add('nb_single')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Album::class,
        ]);
    }
}

mywebsite/src/Controller/AlbumController.php
<?php

namespace App\Controller;

use App\Entity\Album;
use App\Form\AlbumType;
use App\Repository\AlbumRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/album")
 */
class AlbumController extends Controller
{
    /**
     * @Route("/", name="album_index", methods="GET")
     */
    public function index(AlbumRepository $albumRepository): Response
    {
        return $this->render('album/index.html.twig', ['albums' => $albumRepository->findAll()]);
    }

    /**
     * @Route("/new", name="album_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $album = new Album();
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($album);
            $em->flush();

            return $this->redirectToRoute('album_index');
        }

        return $this->render('album/new.html.twig', [
            'album' => $album,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="album_show", methods="GET")
     */
    public function show(Album $album): Response
    {
        return $this->render('album/show.html.twig', ['album' => $album]);
    }

    /**
     * @Route("/{id}/edit", name="album_edit", methods="GET|POST")
     */
    public function edit(Request $request, Album $album): Response
    {
        $form = $this->createForm(AlbumType::class, $album);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('album_edit', ['id' => $album->getId()]);
        }

        return $this->render('album/edit.html.twig', [
            'album' => $album,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="album_delete", methods="DELETE")
     */
    public function delete(Request $request, Album $album): Response
    {
        if ($this->isCsrfTokenValid('delete'.$album->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($album);
            $em->flush();
        }

        return $this->redirectToRoute('album_index');
    }
}

mywebsite/templates/album/_delete_form.html.twig
<form method="post" action="{{ path('album_delete', {'id': album.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ album.id) }}">
    <button class="btn">Delete</button>
</form>

mywebsite/templates/album/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

mywebsite/templates/album/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Album{% endblock %}

{% block body %}
    <h1>Edit Album</h1>

    {{ include('album/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('album_index') }}">back to list</a>

    {{ include('album/_delete_form.html.twig') }}
{% endblock %}

mywebsite/templates/album/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album index{% endblock %}

{% block body %}
    <h1>Album index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Artiste</th>
                <th>Nb_single</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for album in albums %}
            <tr>
                <td>{{ album.id }}</td>
                <td>{{ album.name }}</td>
                <td>{{ album.artiste }}</td>
                <td>{{ album.nbSingle }}</td>
                <td>
                    <a href="{{ path('album_show', {'id': album.id}) }}">show</a>
                    <a href="{{ path('album_edit', {'id': album.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('album_new') }}">Create new</a>
{% endblock %}

mywebsite/templates/album/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Album{% endblock %}

{% block body %}
    <h1>Create new Album</h1>

    {{ include('album/_form.html.twig') }}

    <a href="{{ path('album_index') }}">back to list</a>
{% endblock %}

mywebsite/templates/album/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Album{% endblock %}

{% block body %}
    <h1>Album</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ album.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ album.name }}</td>
            </tr>
            <tr>
                <th>Artiste</th>
                <td>{{ album.artiste }}</td>
            </tr>
            <tr>
                <th>Nb_single</th>
                <td>{{ album.nbSingle }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('album_index') }}">back to list</a>

    <a href="{{ path('album_edit', {'id': album.id}) }}">edit</a>

    {{ include('album/_delete_form.html.twig') }}
{% endblock %}